#include "Body.h"
#pragma optimize("", off)

// ***************       Please cover this file with file generated by key_obf.py      *************** //
// ***************    This is an example of password Dt!5OoxWyIHsh#p~s6LKOmEeRJI44!AW  *************** //
// ***************      DO NOT USE THIS PASSWORD & CODE IN PRODUCTION ENVIRONMENTS     *************** //
namespace EncryptionKey {
unsigned char* f00() {
    static unsigned char part[4];
    unsigned char v08 = static_cast<unsigned char>(141 ^ 34 ^ 200 ^ 185 ^ 136 ^ 47);
    part[0] = v08;
    unsigned char v18 = static_cast<unsigned char>(110 ^ 248 ^ 149 ^ 81);
    part[1] = v18;
    unsigned char v16 = static_cast<unsigned char>(82 ^ 125 ^ 217 ^ 22 ^ 117 ^ 208);
    part[2] = v16;
    unsigned char v12 = static_cast<unsigned char>(206 ^ 155 ^ 25);
    part[3] = v12;
    return part;
}

unsigned char* f01() {
    static unsigned char part[4];
    unsigned char v1c = static_cast<unsigned char>(209 ^ 169 ^ 171 ^ 63 ^ 216);
    part[0] = v1c;
    unsigned char v19 = static_cast<unsigned char>(243 ^ 20 ^ 47 ^ 42 ^ 168);
    part[1] = v19;
    unsigned char v09 = static_cast<unsigned char>(142 ^ 26 ^ 221);
    part[2] = v09;
    unsigned char v0b = static_cast<unsigned char>(230 ^ 229 ^ 112);
    part[3] = v0b;
    return part;
}

unsigned char* f02() {
    static unsigned char part[4];
    unsigned char v17 = static_cast<unsigned char>(125 ^ 68 ^ 92);
    part[0] = v17;
    unsigned char v1b = static_cast<unsigned char>(42 ^ 165 ^ 26 ^ 161);
    part[1] = v1b;
    unsigned char v15 = static_cast<unsigned char>(5 ^ 187 ^ 192 ^ 211 ^ 164 ^ 100);
    part[2] = v15;
    unsigned char v02 = static_cast<unsigned char>(233 ^ 150 ^ 202 ^ 148);
    part[3] = v02;
    return part;
}

unsigned char* f03() {
    static unsigned char part[4];
    unsigned char v05 = static_cast<unsigned char>(12 ^ 236 ^ 143);
    part[0] = v05;
    unsigned char v00 = static_cast<unsigned char>(4 ^ 148 ^ 236 ^ 137 ^ 177);
    part[1] = v00;
    unsigned char v11 = static_cast<unsigned char>(132 ^ 66 ^ 115 ^ 134 ^ 5);
    part[2] = v11;
    unsigned char v13 = static_cast<unsigned char>(221 ^ 121 ^ 82 ^ 189);
    part[3] = v13;
    return part;
}

unsigned char* f04() {
    static unsigned char part[4];
    unsigned char v1d = static_cast<unsigned char>(251 ^ 95 ^ 155 ^ 1 ^ 31);
    part[0] = v1d;
    unsigned char v07 = static_cast<unsigned char>(51 ^ 22 ^ 9 ^ 123);
    part[1] = v07;
    unsigned char v0a = static_cast<unsigned char>(216 ^ 91 ^ 185 ^ 62 ^ 236 ^ 160);
    part[2] = v0a;
    unsigned char v1a = static_cast<unsigned char>(8 ^ 112 ^ 197 ^ 244);
    part[3] = v1a;
    return part;
}

unsigned char* f05() {
    static unsigned char part[4];
    unsigned char v1e = static_cast<unsigned char>(119 ^ 67 ^ 252 ^ 116 ^ 253);
    part[0] = v1e;
    unsigned char v0f = static_cast<unsigned char>(66 ^ 231 ^ 219);
    part[1] = v0f;
    unsigned char v10 = static_cast<unsigned char>(236 ^ 154 ^ 5);
    part[2] = v10;
    unsigned char v04 = static_cast<unsigned char>(160 ^ 64 ^ 10 ^ 182 ^ 19);
    part[3] = v04;
    return part;
}

unsigned char* f06() {
    static unsigned char part[4];
    unsigned char v14 = static_cast<unsigned char>(218 ^ 137 ^ 77 ^ 228 ^ 62 ^ 139);
    part[0] = v14;
    unsigned char v0e = static_cast<unsigned char>(38 ^ 146 ^ 251 ^ 63);
    part[1] = v0e;
    unsigned char v0d = static_cast<unsigned char>(9 ^ 185 ^ 35 ^ 31 ^ 175);
    part[2] = v0d;
    unsigned char v0c = static_cast<unsigned char>(20 ^ 215 ^ 225 ^ 154 ^ 208);
    part[3] = v0c;
    return part;
}

unsigned char* f07() {
    static unsigned char part[4];
    unsigned char v06 = static_cast<unsigned char>(201 ^ 14 ^ 191);
    part[0] = v06;
    unsigned char v1f = static_cast<unsigned char>(70 ^ 43 ^ 237 ^ 215);
    part[1] = v1f;
    unsigned char v01 = static_cast<unsigned char>(67 ^ 202 ^ 223 ^ 238 ^ 204);
    part[2] = v01;
    unsigned char v03 = static_cast<unsigned char>(7 ^ 49 ^ 129 ^ 27 ^ 153);
    part[3] = v03;
    return part;
}
}

std::array<uint8_t, 32> ResourcePack::get_aes_key() {
    std::array<uint8_t, 32> key = {};
    unsigned char* seg;
    seg = EncryptionKey::f00(); key[8] = seg[0];
    seg = EncryptionKey::f00(); key[24] = seg[1];
    seg = EncryptionKey::f00(); key[22] = seg[2];
    seg = EncryptionKey::f00(); key[18] = seg[3];
    seg = EncryptionKey::f01(); key[28] = seg[0];
    seg = EncryptionKey::f01(); key[25] = seg[1];
    seg = EncryptionKey::f01(); key[9] = seg[2];
    seg = EncryptionKey::f01(); key[11] = seg[3];
    seg = EncryptionKey::f02(); key[23] = seg[0];
    seg = EncryptionKey::f02(); key[27] = seg[1];
    seg = EncryptionKey::f02(); key[21] = seg[2];
    seg = EncryptionKey::f02(); key[2] = seg[3];
    seg = EncryptionKey::f03(); key[5] = seg[0];
    seg = EncryptionKey::f03(); key[0] = seg[1];
    seg = EncryptionKey::f03(); key[17] = seg[2];
    seg = EncryptionKey::f03(); key[19] = seg[3];
    seg = EncryptionKey::f04(); key[29] = seg[0];
    seg = EncryptionKey::f04(); key[7] = seg[1];
    seg = EncryptionKey::f04(); key[10] = seg[2];
    seg = EncryptionKey::f04(); key[26] = seg[3];
    seg = EncryptionKey::f05(); key[30] = seg[0];
    seg = EncryptionKey::f05(); key[15] = seg[1];
    seg = EncryptionKey::f05(); key[16] = seg[2];
    seg = EncryptionKey::f05(); key[4] = seg[3];
    seg = EncryptionKey::f06(); key[20] = seg[0];
    seg = EncryptionKey::f06(); key[14] = seg[1];
    seg = EncryptionKey::f06(); key[13] = seg[2];
    seg = EncryptionKey::f06(); key[12] = seg[3];
    seg = EncryptionKey::f07(); key[6] = seg[0];
    seg = EncryptionKey::f07(); key[31] = seg[1];
    seg = EncryptionKey::f07(); key[1] = seg[2];
    seg = EncryptionKey::f07(); key[3] = seg[3];
    return key;
}
#pragma optimize("", on)